version: 2
jobs:
  build:
    docker:
      - image: docker:19.03.0 
    steps:
      - run:
            name: Install Prereqs
            command: |
              apk add --update git
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build 
          command: |
            apk add --update python openssh git curl
            BRANCH=${CIRCLE_BRANCH#*/}
            VERSION=`cat VERSION`
            FROM_RP_TAG=v5.0.0
            if [[ ! -z $CIRCLE_TAG ]]; then
              VERSION_TAG="${VERSION}"
            elif [[ $BRANCH == develop ]]; then
              VERSION_TAG="${VERSION}-dev"
            else
              VERSION_TAG="ci-${VERSION}-${BRANCH}"
            fi
            docker login -u $DOCKER_USER -p $DOCKER_PASS

            # Build the container with default branding
            docker build --build-arg VERSION_TAG=$VERSION_TAG -t istresearch/rapidpro:${VERSION_TAG} -f Dockerfile .
            docker push istresearch/rapidpro:${VERSION_TAG}

            # Build the container with Engage branding
            docker build --build-arg VERSION_TAG=$VERSION_TAG -t istresearch/p4-engage:${VERSION_TAG} -f Dockerfile-engage .
            docker push istresearch/p4-engage:${VERSION_TAG}
            if [[ $BRANCH == develop ]]; then
              docker tag istresearch/p4-engage:${VERSION_TAG} istresearch/p4-engage:ci-develop
              docker push istresearch/p4-engage:ci-develop
            fi

            # Build the container with generic branding
            docker build --build-arg VERSION_TAG=$VERSION_TAG -t istresearch/rapidpro:${VERSION_TAG}-generic -f Dockerfile-generic .
            docker push istresearch/rapidpro:${VERSION_TAG}-generic
      - run:
          name: Deploy
          command: |
            BRANCH=${CIRCLE_BRANCH#*/}
            if [[ $BRANCH == develop ]] || [[ $BRANCH == master ]]; then
              curl --user ${CIRCLE_API_USER_TOKEN}: --data build_parameters[CIRCLE_JOB]=eks_deploy --data build_parameters[DEPLOY_PROJECT]=pulse-engage https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/p4-deploy/tree/develop
            else
              echo "Skipping deploy step"
            fi
        
workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          context: globalconfig
          filters:
            tags:
              ignore: /^test-.*/
